import type {
  BulletinBoard,
  BulletinPost,
  Cohort,
  Profile,
  RosterInvite,
  SessionLog,
} from "@/types/portal";

/**
 * Seed data for the interactive prototype. All user-facing copy is in
 * Simplified Chinese. This stands in for the eventual Supabase data while we
 * gather team feedback; the store layer hydrates from it on first load.
 */

export const mockCohorts: Cohort[] = [
  {
    id: "cohort-2025-spring",
    name: "她行 2025 春季项目",
    starts_at: "2025-03-01",
    ends_at: "2025-06-30",
    bulletin_open: true,
    created_at: "2025-02-15T00:00:00Z",
  },
  {
    id: "cohort-2024-fall",
    name: "她行 2024 秋季项目",
    starts_at: "2024-09-01",
    ends_at: "2024-12-31",
    bulletin_open: false,
    created_at: "2024-08-15T00:00:00Z",
  },
];

const avatar = (seed: string) =>
  `https://api.dicebear.com/9.x/avataaars/svg?seed=${encodeURIComponent(seed)}`;

export const mockProfiles: Profile[] = [
  {
    id: "admin-1",
    role: "admin",
    cohort_ids: ["cohort-2025-spring", "cohort-2024-fall"],
    full_name: "管理员·林夏",
    email: "admin@taxing.org",
    bio: "她行项目运营负责人，负责名单导入与进度跟踪。",
    background: "多年公益项目运营经验。",
    interests: ["项目管理", "社区运营"],
    goals: "让每一对导师与学员都顺利完成项目。",
    linkedin: "https://www.linkedin.com/in/taxing-admin",
    avatar_url: avatar("admin-lin-xia"),
    visible: false,
    created_at: "2025-02-16T00:00:00Z",
    updated_at: "2025-02-16T00:00:00Z",
  },

  // Mentors
  {
    id: "mentor-1",
    role: "mentor",
    cohort_ids: ["cohort-2025-spring", "cohort-2024-fall"],
    full_name: "王静",
    email: "wangjing@example.com",
    bio: "资深产品经理，专注于 B 端产品设计与团队管理。",
    background: "10 年互联网产品经验，现就职于一家头部科技公司。",
    interests: ["产品管理", "职业规划", "女性领导力"],
    goals: "帮助学员建立清晰的职业路径。",
    linkedin: "https://www.linkedin.com/in/wangjing",
    avatar_url: avatar("wang-jing"),
    visible: true,
    created_at: "2025-03-01T00:00:00Z",
    updated_at: "2025-03-01T00:00:00Z",
  },
  {
    id: "mentor-2",
    role: "mentor",
    cohort_ids: ["cohort-2025-spring"],
    full_name: "李梅",
    email: "limei@example.com",
    bio: "数据科学家，热爱用数据讲故事。",
    background: "统计学博士，曾在金融与电商行业从事数据建模。",
    interests: ["数据科学", "机器学习", "求职面试"],
    goals: "带领学员入门数据分析并完成一个实战项目。",
    linkedin: "https://www.linkedin.com/in/limei",
    avatar_url: avatar("li-mei"),
    visible: true,
    created_at: "2025-03-01T00:00:00Z",
    updated_at: "2025-03-01T00:00:00Z",
  },
  {
    id: "mentor-3",
    role: "mentor",
    cohort_ids: ["cohort-2025-spring"],
    full_name: "张晓琳",
    email: "zhangxiaolin@example.com",
    bio: "用户体验设计负责人，关注无障碍设计。",
    background: "设计专业出身，带过多支跨职能设计团队。",
    interests: ["用户体验", "设计思维", "作品集"],
    goals: "帮助学员打磨设计作品集。",
    linkedin: "https://www.linkedin.com/in/zhangxiaolin",
    avatar_url: avatar("zhang-xiaolin"),
    visible: true,
    created_at: "2025-03-01T00:00:00Z",
    updated_at: "2025-03-01T00:00:00Z",
  },
  {
    id: "mentor-4",
    role: "mentor",
    cohort_ids: ["cohort-2025-spring"],
    full_name: "陈安琪",
    email: "chenanqi@example.com",
    bio: "软件工程师，开源项目贡献者。",
    background: "后端工程背景，热衷于技术分享与 mentorship。",
    interests: ["软件工程", "后端开发", "技术面试"],
    goals: "陪伴学员完成第一次技术岗位的求职。",
    linkedin: "https://www.linkedin.com/in/chenanqi",
    avatar_url: avatar("chen-anqi"),
    visible: true,
    created_at: "2025-03-01T00:00:00Z",
    updated_at: "2025-03-01T00:00:00Z",
  },
  {
    id: "mentor-5",
    role: "mentor",
    cohort_ids: ["cohort-2024-fall"],
    full_name: "刘洋",
    email: "liuyang@example.com",
    bio: "市场营销总监，擅长品牌策略。",
    background: "消费品行业 12 年，主导过多个全国性营销活动。",
    interests: ["市场营销", "品牌策略", "职场沟通"],
    goals: "帮助学员理解市场岗位的核心能力。",
    linkedin: "https://www.linkedin.com/in/liuyang",
    avatar_url: avatar("liu-yang"),
    visible: true,
    created_at: "2024-09-01T00:00:00Z",
    updated_at: "2024-09-01T00:00:00Z",
  },

  // Mentees
  {
    id: "mentee-1",
    role: "mentee",
    cohort_ids: ["cohort-2025-spring"],
    full_name: "赵欣怡",
    email: "zhaoxinyi@example.com",
    bio: "应届毕业生，希望进入产品经理岗位。",
    background: "计算机与商科双学位，做过两段产品实习。",
    interests: ["产品管理", "求职面试", "职业规划"],
    goals: "在三个月内拿到产品经理的实习或全职 offer。",
    linkedin: "https://www.linkedin.com/in/zhaoxinyi",
    avatar_url: avatar("zhao-xinyi"),
    visible: true,
    created_at: "2025-03-02T00:00:00Z",
    updated_at: "2025-03-02T00:00:00Z",
  },
  {
    id: "mentee-2",
    role: "mentee",
    cohort_ids: ["cohort-2025-spring"],
    full_name: "孙佳",
    email: "sunjia@example.com",
    bio: "转行中的数据分析爱好者。",
    background: "文科背景，自学 SQL 与 Python。",
    interests: ["数据科学", "机器学习", "转行"],
    goals: "完成一个完整的数据分析项目并写进简历。",
    linkedin: "https://www.linkedin.com/in/sunjia",
    avatar_url: avatar("sun-jia"),
    visible: true,
    created_at: "2025-03-02T00:00:00Z",
    updated_at: "2025-03-02T00:00:00Z",
  },
  {
    id: "mentee-3",
    role: "mentee",
    cohort_ids: ["cohort-2025-spring", "cohort-2024-fall"],
    full_name: "周敏",
    email: "zhoumin@example.com",
    bio: "设计在校生，正在准备作品集。",
    background: "视觉传达专业大三学生。",
    interests: ["用户体验", "设计思维", "作品集"],
    goals: "在导师指导下完成两个完整的 UX 案例。",
    linkedin: "https://www.linkedin.com/in/zhoumin",
    avatar_url: avatar("zhou-min"),
    visible: true,
    created_at: "2025-03-02T00:00:00Z",
    updated_at: "2025-03-02T00:00:00Z",
  },
  {
    id: "mentee-4",
    role: "mentee",
    cohort_ids: ["cohort-2025-spring"],
    full_name: "吴雨桐",
    email: "wuyutong@example.com",
    bio: "计算机专业学生，目标后端开发工程师。",
    background: "刷题中，准备技术面试。",
    interests: ["软件工程", "后端开发", "技术面试"],
    goals: "通过大厂技术面试。",
    linkedin: "https://www.linkedin.com/in/wuyutong",
    avatar_url: avatar("wu-yutong"),
    visible: true,
    created_at: "2025-03-02T00:00:00Z",
    updated_at: "2025-03-02T00:00:00Z",
  },
  {
    id: "mentee-5",
    role: "mentee",
    cohort_ids: ["cohort-2025-spring"],
    full_name: "郑思源",
    email: "zhengsiyuan@example.com",
    bio: "希望提升职场沟通与领导力。",
    background: "工作两年的运营专员。",
    interests: ["女性领导力", "职场沟通", "职业规划"],
    goals: "争取晋升为团队负责人。",
    linkedin: "https://www.linkedin.com/in/zhengsiyuan",
    avatar_url: avatar("zheng-siyuan"),
    visible: true,
    created_at: "2025-03-02T00:00:00Z",
    updated_at: "2025-03-02T00:00:00Z",
  },
  {
    id: "mentee-6",
    role: "mentee",
    cohort_ids: ["cohort-2024-fall"],
    full_name: "黄丽",
    email: "huangli@example.com",
    bio: "市场方向求职者。",
    background: "广告学专业，做过社媒运营实习。",
    interests: ["市场营销", "品牌策略", "求职面试"],
    goals: "进入消费品公司的市场岗位。",
    linkedin: "https://www.linkedin.com/in/huangli",
    avatar_url: avatar("huang-li"),
    visible: true,
    created_at: "2024-09-02T00:00:00Z",
    updated_at: "2024-09-02T00:00:00Z",
  },
];

export const mockBoards: BulletinBoard[] = [
  {
    id: "board-friends-spring",
    cohort_id: "cohort-2025-spring",
    name: "活动初期交友留言板",
    description: "项目刚开始，来这里互相认识、寻找志同道合的伙伴吧！",
    is_open: true,
    created_at: "2025-03-02T00:00:00Z",
  },
  {
    id: "board-growth-spring",
    cohort_id: "cohort-2025-spring",
    name: "每周成长打卡板",
    description: "记录你的每周进展，互相鼓励，坚持到底。",
    is_open: true,
    created_at: "2025-03-02T00:00:00Z",
  },
  {
    id: "board-graduation-spring",
    cohort_id: "cohort-2025-spring",
    name: "毕业留言板 🎓",
    description: "项目结束时，在这里留下你的感谢与祝福。",
    is_open: false,
    created_at: "2025-03-02T00:00:00Z",
  },
  {
    id: "board-friends-fall",
    cohort_id: "cohort-2024-fall",
    name: "2024 秋季交流板",
    description: "2024 秋季项目的综合交流区。",
    is_open: false,
    created_at: "2024-09-02T00:00:00Z",
  },
];

export const mockBulletinPosts: BulletinPost[] = [
  {
    id: "post-1",
    cohort_id: "cohort-2025-spring",
    board_id: "board-friends-spring",
    author_id: "mentee-1",
    category: "wish",
    body: "希望能找到有产品经理经验的导师，聊聊如何准备产品面试，谢谢大家！",
    hidden: false,
    created_at: "2025-03-05T09:30:00Z",
  },
  {
    id: "post-2",
    cohort_id: "cohort-2025-spring",
    board_id: "board-friends-spring",
    author_id: "mentee-2",
    category: "thanks",
    body: "非常感谢李梅导师上周的指导，帮我理清了数据分析的学习路线，受益匪浅！",
    hidden: false,
    created_at: "2025-03-08T14:00:00Z",
  },
  {
    id: "post-3",
    cohort_id: "cohort-2025-spring",
    board_id: "board-growth-spring",
    author_id: "mentee-4",
    category: "growth",
    body: "本周完成了三道算法题并整理了笔记，离技术面试又近了一步，继续加油！",
    hidden: false,
    created_at: "2025-03-10T20:15:00Z",
  },
  {
    id: "post-4",
    cohort_id: "cohort-2025-spring",
    board_id: "board-friends-spring",
    author_id: "mentee-3",
    category: "other",
    body: "有没有同样在准备 UX 作品集的小伙伴？想组个互助小组一起复盘。",
    hidden: false,
    created_at: "2025-03-12T11:45:00Z",
  },
  {
    id: "post-5",
    cohort_id: "cohort-2025-spring",
    board_id: "board-growth-spring",
    author_id: "mentee-5",
    category: "wish",
    body: "想请教如何在团队中提升影响力，期待和有管理经验的导师交流。",
    hidden: true,
    created_at: "2025-03-13T08:20:00Z",
  },
];

export const mockSessions: SessionLog[] = [
  {
    id: "session-1",
    cohort_id: "cohort-2025-spring",
    mentor_id: "mentor-1",
    mentee_id: "mentee-1",
    session_date: "2025-03-06",
    notes: "首次见面，明确了产品经理求职目标与时间线。",
    created_by: "admin-1",
    created_at: "2025-03-06T10:00:00Z",
  },
  {
    id: "session-2",
    cohort_id: "cohort-2025-spring",
    mentor_id: "mentor-1",
    mentee_id: "mentee-1",
    session_date: "2025-03-13",
    notes: "模拟产品面试，复盘了案例分析的思路。",
    created_by: "admin-1",
    created_at: "2025-03-13T10:00:00Z",
  },
  {
    id: "session-3",
    cohort_id: "cohort-2025-spring",
    mentor_id: "mentor-2",
    mentee_id: "mentee-2",
    session_date: "2025-03-07",
    notes: "制定数据分析学习计划，布置了第一个练习项目。",
    created_by: "admin-1",
    created_at: "2025-03-07T15:00:00Z",
  },
  {
    id: "session-4",
    cohort_id: "cohort-2025-spring",
    mentor_id: "mentor-4",
    mentee_id: "mentee-4",
    session_date: "2025-03-09",
    notes: "讲解后端系统设计基础，推荐了学习资料。",
    created_by: "admin-1",
    created_at: "2025-03-09T19:00:00Z",
  },
];

export const mockRosterInvites: RosterInvite[] = [];

export type MockDb = {
  cohorts: Cohort[];
  profiles: Profile[];
  bulletin_boards: BulletinBoard[];
  bulletin_posts: BulletinPost[];
  sessions_log: SessionLog[];
  roster_invites: RosterInvite[];
};

export function seedDb(): MockDb {
  return {
    cohorts: structuredClone(mockCohorts),
    profiles: structuredClone(mockProfiles),
    bulletin_boards: structuredClone(mockBoards),
    bulletin_posts: structuredClone(mockBulletinPosts),
    sessions_log: structuredClone(mockSessions),
    roster_invites: structuredClone(mockRosterInvites),
  };
}

/** Identities offered by the dev account switcher in the prototype. */
export const demoAccountIds = ["admin-1", "mentor-1", "mentee-1"] as const;
